home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.main_page, name='main_page'),
]

profiles/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.update_profile_page, name='update_profile_page'),
    path('register/', views.register_page, name='register_page'),
    path('login/', views.login_page, name='login_page'),
    path('logout/', views.logout_page, name='logout_page'),
    path('delete/', views.delete_user_page, name='delete_user_page'),
]

scrapyard/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('user/', include('profiles.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profiles/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid


class Profile(models.Model):
    id = models.UUIDField(
        default=uuid.uuid4,
        unique=True,
        primary_key=True,
        editable=False
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=20)
    surname = models.CharField(max_length=30)
    address_1 = models.CharField(max_length=100)
    address_2 = models.CharField(max_length=100, null=True, blank=True)
    postal_code = models.CharField(max_length=10)
    city = models.CharField(max_length=100)
    country = models.CharField(max_length=50)
    phone_number = models.IntegerField(null=True, blank=True)
    email = models.CharField(max_length=60)

    def __str__(self):
        return f"{self.first_name} {self.surname}"

profiles/forms.py
from django.forms import ModelForm, TextInput
from .models import Profile


class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        exclude = [
            'id',
            'user'
        ]
        widgets = {
            'phone_number': TextInput()
        }

home/views.py
from django.shortcuts import render


def main_page(request):
    """ Render main page """

    return render(request, 'home/home.html')

profiles/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages
from django.contrib.auth.models import User
from .signals import profile_send, user_update
from .forms import ProfileForm


def register_page(request):
    """ Render register page """

    if request.method == 'POST':
        # Create dictionary with form responses
        response = {
            'first_name': request.POST.get('first_name'),
            'last_name': request.POST.get('last_name'),
            'email': request.POST.get('email'),
            'password': request.POST.get('password'),
            'address1': request.POST.get('address1'),
            'address2': request.POST.get('address2'),
            'city': request.POST.get('city'),
            'country': request.POST.get('country'),
            'postcode': request.POST.get('postcode'),
            'phone_number': request.POST.get('phone_number')
        }

        # Create User object
        User.objects.create_user(
            username=response['email'],
            password=response['password'],
            email=response['email'],
            first_name=response['first_name'],
            last_name=response['last_name']
        )

        # Get user object
        user = User.objects.get(username=response['email'])

        # Send signal to create Profile object
        profile_send.send(
            sender=profile_send,
            user=user,
            response=response
        )

        login(request, user)
        return redirect('main_page')

    return render(request, 'profiles/register.html')


def login_page(request):
    """ Render login page """

    if request.method == 'POST':

        # Create dictionary from form elements
        response = {
            'username': request.POST.get('email'),
            'password': request.POST.get('password')
        }

        # Check if username exists
        try:
            user = User.objects.get(username=response['username'])
        except:  # noqa: E722
            messages.error(request, 'Incorrect Username')
        else:
            # Authenticate user
            user = authenticate(
                request,
                username=response['username'],
                password=response['password']
            )

            # Log user in
            if user is not None:
                login(request, user)
                return redirect('main_page')
            else:
                messages.error(request, 'Incorrect Username / Password')

    return render(request, 'profiles/login.html')


def logout_page(request):
    """ Kill user's session and redirect to main page """

    logout(request)
    messages.info(request, "You've been logged out!")
    return redirect('main_page')


def update_profile_page(request):
    """ Render page to update Profile """
    # Get profile instance
    profile = request.user.profile

    if request.method == 'POST':
        # Store previous username
        username = request.user.username

        form = ProfileForm(request.POST, instance=profile)

        if form.is_valid():
            form.save()
            # Send signal to update User
            user_update.send(
                sender=user_update,
                username=username
            )
            messages.info(request, 'Profile updated!')
            return redirect('main_page')

    form = ProfileForm(instance=profile)

    context = {
        'form': form
    }

    return render(request, 'profiles/user_settings.html', context)


def delete_user_page(request):
    """ Delete user profile """

    try:
        user = User.objects.get(id=request.user.id)
        user.delete()
        messages.info(request, 'User deleted!')
    except:  # noqa: E722
        messages.error(request, 'Internal error, please try again.')
    finally:
        return redirect('main_page')

home/templates/home/home.html
{% extends 'main.html' %}
{% load static %}

{% block content %}
    <div class="container-fluid home-text">
        <div class="content">
            <h1 class="text-center">Welcome to ScrapYard</h1>
            <h3 class="text-center">We find. We fix. We sell.</h2>
        </div>
    </div>
{% endblock %}

profiles/templates/profiles/login.html
{% extends 'main.html' %}
{% load static %}

{% block content %}

    <div class="container-fluid login-page">
        <div class="content">
            
            <h3 class="text-center">Login</h3>

            <form action="{% url 'login_page' %}" method='POST'>
                {% csrf_token %}

                <div class="form-row justify-content-center row-eq-spacing">
                    <div class="col-md-3">
                        <label for="email">Email</label>
                        <input type="email" id="email" name="email" placeholder="Your email address" required="required">
                    </div>
                </div>

                <div class="form-row justify-content-center row-eq-spacing">
                    <div class="col-md-3">
                        <label for="password">Password</label>
                        <input type="password" id="password" name="password" placeholder="Your password" required="required">
                    </div>
                </div>

                <div class="form-row justify-content-center row-eq-spacing">
                    <input class="btn login-button" type="submit" value="Login">
                </div>

            </form>

        </div>
    </div>

{% endblock %}

profiles/templates/profiles/register.html
{% extends 'main.html' %}
{% load static %}

{% block content %}
    <div class="container-fluid register-page">
        <div class="content">

            <h3 class="text-center">Create a Profile</h3>

            <form action="{% url 'register_page' %}" method="POST">
                {% csrf_token %}

                <!-- Personal Information -->
                <div class="form-row justify-content-center row-eq-spacing">
                    <div class="col-md-3">
                        <label for="first_name" class="required">First Name</label>
                        <input type="text" id="first_name" name="first_name" placeholder="i.e. John" required="required">
                    </div>
                    <div class="col-md-3">
                        <label for="last_name" class="required">Last Name</label>
                        <input type="text" id="last_name" name="last_name" placeholder="i.e. Smith" required="required">
                    </div>
                </div>

                <!-- Login Information -->
                <div class="form-row justify-content-center row-eq-spacing">
                    <div class="col-md-3">
                        <label for="email" class="required">Email</label>
                        <input type="email" id="email" name="email" placeholder="Your email address" required="required">
                    </div>
                    <div class="col-md-3">
                        <label for="password" class="required">Password</label>
                        <input type="password" id="password" name="password" placeholder="Type in a password" required="required">
                    </div>
                </div>

                <!-- Address Information -->
                <div class="form-row justify-content-center row-eq-spacing">
                    <div class="col-md-3">
                        <label for="address1" class="required">Address 1</label>
                        <input type="text" id="address1" name="address1" placeholder="i.e. 23 Posh Building" required="required">
                    </div>
                    <div class="col-md-3">
                        <label for="address2">Address 2</label>
                        <input type="text" id="address2" name="address2" placeholder="i.e. Canary Road">
                    </div>
                </div>

                <div class="form-row justify-content-center row-eq-spacing">
                    <div class="col-md-3">
                        <label for="city" class="required">City</label>
                        <input type="text" id="city" name="city" placeholder="i.e. London" required="required">
                    </div>
                    <div class="col-md-3">
                        <label for="country" class="required">Country</label>
                        <input type="text" id="country" name="country" placeholder="i.e. England" required="required">
                    </div>
                </div>

                <div class="form-row justify-content-center row-eq-spacing">
                    <div class="col-md-3">
                        <label for="postcode" class="required">Postcode</label>
                        <input type="text" id="postcode" name="postcode" placeholder="i.e. NW1 6AS" required="required">
                    </div>
                    <div class="col-md-3">
                        <label for="phone_number">Phone Number</label>
                        <input type="text" id="phone_number" name="phone_number" placeholder="i.e. 07123456789">
                    </div>
                </div>

                <!-- Submit Button -->
                <div class="form-row justify-content-center row-eq-spacing">
                    <input class="btn register-button" type="submit" value="Register">
                </div>

            </form>
        </div>
    </div>
{% endblock %}

profiles/templates/profiles/user_settings.html
{% extends 'main.html' %}
{% load static %}
{% block content %}
<div class="container-fluid register-page">
    <div class="content">

        <h3 class="text-center">Update Profile Settings</h3>

        <form action="{% url 'update_profile_page' %}" method="POST">
            {% csrf_token %}

            <!-- Personal Information -->
            <div class="form-row justify-content-center row-eq-spacing">
                <div class="col-md-3">
                    <label for="id_first_name" class="required">First Name</label>
                    {{ form.first_name }}
                </div>
                <div class="col-md-3">
                    <label for="id_surname" class="required">Last Name</label>
                    {{ form.surname }}
                </div>
            </div>

            <!-- Login Information -->
            <div class="form-row justify-content-center row-eq-spacing">
                <div class="col-md-6">
                    <label for="id_email" class="required">Email</label>
                    {{ form.email }}
                </div>
            </div>

            <!-- Address Information -->
            <div class="form-row justify-content-center row-eq-spacing">
                <div class="col-md-3">
                    <label for="id_address1" class="required">Address 1</label>
                    {{ form.address_1 }}
                </div>
                <div class="col-md-3">
                    <label for="id_address2">Address 2</label>
                    {{ form.address_2 }}
                </div>
            </div>

            <div class="form-row justify-content-center row-eq-spacing">
                <div class="col-md-3">
                    <label for="id_city" class="required">City</label>
                    {{ form.city }}
                </div>
                <div class="col-md-3">
                    <label for="id_country" class="required">Country</label>
                    {{ form.country }}
                </div>
            </div>

            <div class="form-row justify-content-center row-eq-spacing">
                <div class="col-md-3">
                    <label for="id_postal_code" class="required">Postcode</label>
                    {{ form.postal_code }}
                </div>
                <div class="col-md-3">
                    <label for="id_phone_number">Phone Number</label>
                    {{ form.phone_number }}
                </div>
            </div>

            <!-- Buttons -->
            <div class="form-row justify-content-center row-eq-spacing">
                <input class="btn update-button" type="submit" value="Update">
                <a href="{% url 'delete_user_page' %}" class="btn delete-button">Delete</a>
            </div>

        </form>
    </div>
</div>
{% endblock %}

templates/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

    <head>

        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <!-- Google Fonts -->
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Barriecito&family=Montserrat:wght@100;200;300;400;500;600;700&display=swap" rel="stylesheet">

        <!-- Halfmoon CSS -->
        <link href="https://cdn.jsdelivr.net/npm/halfmoon@1.1.1/css/halfmoon-variables.min.css" rel="stylesheet" />

        <!-- Internal CSS -->
        <link rel="stylesheet" href="{% static 'styles/main.css' %}">

        <title>ScrapYard</title>

    </head>

    <body>

    <div class="page-wrapper">
        <header>
            {% include 'navbar.html' %}
        </header>

        <main>
            <!-- Flash messages -->
            {% if messages %}
                {% for message in messages %}
                    <h4 class="text-center messages {{ message.tags }}">{{ message }}</h4>
                {% endfor %}
            {% endif %}

            {% block content %}
            {% endblock %}
        </main>

        <footer>
        <p>&copy; ScrapYard 2021</p>
        <a href="#">About</a>
        </footer>

        </div>

        <!-- Halfmoon JS -->
        <script src="https://cdn.jsdelivr.net/npm/halfmoon@1.1.1/js/halfmoon.min.js"></script>

    </body>

</html>

templates/navbar.html
<nav class="navbar">
    <!-- Navbar brand -->
    <a href="{% url 'main_page' %}" class="navbar-logo">ScrapYard</a>

    <!-- Navbar nav -->
    <ul class="navbar-nav d-none d-md-flex links">
      {% if request.user.is_authenticated %}
      <!-- Dropdown Menu -->
        <div class="dropdown">
          <button class="btn logged-in-menu" data-toggle="dropdown" type="button" id="dropdown-toggle-btn-1" aria-haspopup="true" aria-expanded="false">
            Welcome {{user.first_name}}!
          </button>
          <div class="dropdown-menu logged-in-menu" aria-labelledby="dropdown-toggle-btn-1">
            <a href="{% url 'update_profile_page' %}" class="dropdown-item">Profile Settings</a>
            <a href="#" class="dropdown-item">My orders</a>
          </div>
        </div>
        <!-- Logout Button -->
        <li class="nav-item">
          <a href="{% url 'logout_page' %}" class="nav-link">Logout</a>
        </li>
      {% else %}
        <li class="nav-item">
          <a href="{% url 'login_page' %}" class="nav-link">Login</a>
        </li>
        <li class="nav-item">
          <a href="{% url 'register_page' %}" class="nav-link">Register</a>
        </li>
      {% endif %}
    </ul>

    <!-- Navbar content (with the dropdown menu) -->
    <div class="navbar-content d-md-none ml-auto"> <!-- d-md-none = display: none on medium screens and up (width > 768px), ml-auto = margin-left: auto -->
      <div class="dropdown with-arrow">
        <button class="btn" data-toggle="dropdown" type="button" id="navbar-dropdown-toggle-btn-1">
          Menu
          <i class="fa fa-angle-down" aria-hidden="true"></i>
        </button>
        <div class="dropdown-menu dropdown-menu-right w-200" aria-labelledby="navbar-dropdown-toggle-btn-1"> <!-- w-200 = width: 20rem (200px) -->
          <a href="#" class="dropdown-item">Login</a>
          <a href="" class="dropdown-item">Register</a>
        </div>
      </div>
    </div>
  </nav>